version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.1.0
    ports: 
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "acv-events:1:1, acv-commands:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
