// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projections.Infrastructure;

namespace Projections.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectionsContext))]
    [Migration("20190122152320_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Projections.Domain.Models.Usage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<Guid>("IdentityUserId");

                    b.Property<DateTime>("LastBid");

                    b.Property<DateTime>("LastLogin");

                    b.Property<Guid>("OrgId");

                    b.Property<string>("OrgName");

                    b.Property<Guid>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.HasIndex("FullName");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgName");

                    b.HasIndex("UserId");

                    b.ToTable("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
